version: "3.8"

services:
  zookeeper:
    image:  confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
  kafka1:
    image:  confluentinc/cp-kafka:7.5.0
    container_name: kafka1
    ports:
      - "9001:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
          test: ["CMD", "nc", "-z", "localhost", "9092"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    depend_on:
      - zookeeper
    network:
      - app-global-network
  kafka2:
    image:  confluentinc/cp-kafka:7.5.0
    container_name: kafka2
    ports:
      - "9002:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
          test: ["CMD", "nc", "-z", "localhost", "9092"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    depend_on:
      - zookeeper
    network:
      - app-global-network
network:
  app-global-network:
    external:true


