version: "3.8"

services:
  zookeeper:
    image:  confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    port:
      - "2181:2181"
    environment:
       ZOOKEEPER_CLIENT_PORT: 2181
       ZOOKEEPER_TICK_TIME: 2000
  kafka1:
    image:  confluentinc/cp-zookeeper:7.5.0
    container_name: kafka1
    port:
      - "9001:9001"
    enviroment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depend_on:
      - zookeeper
    network:
      - app-global-network
  kafka2:
    image:  confluentinc/cp-zookeeper:7.5.0
    container_name: kafka2
    port:
      - "9002:9002"
    enviroment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9002
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depend_on:
      - zookeeper
    network:
      - app-global-network
network:
  app-global-network:
    external:true


