version: "3.8"

services:
  redis1:
    image: redis:7.2-alpine
    container_name: redis1
    ports:
      - "5000:5000"
      - "15000:15000"
    command: >
      redis-server --port 5000
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5000
                   --cluster-announce-bus-port 15000
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5000" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis1-data:/data
    networks:
      - app-global-network

  redis2:
    image: redis:7.2-alpine
    container_name: redis2
    ports:
      - "5001:5001"
      - "15001:15001"
    command: >
      redis-server --port 5001
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5001
                   --cluster-announce-bus-port 15001
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5001" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis2-data:/data
    networks:
      - app-global-network


  redis3:
    image: redis:7.2-alpine
    container_name: redis3
    ports:
      - "5002:5002"
      - "15002:15002"
    command: >
      redis-server --port 5002
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5002
                   --cluster-announce-bus-port 15002
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5002" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis3-data:/data
    networks:
      - app-global-network


  redis4:
    image: redis:7.2-alpine
    container_name: redis4
    ports:
      - "5003:5003"
      - "15003:15003"
    command: >
      redis-server --port 5003
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5003
                   --cluster-announce-bus-port 15003
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5003" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis4-data:/data
    networks:
      - app-global-network


  redis5:
    image: redis:7.2-alpine
    container_name: redis5
    ports:
      - "5004:5004"
      - "15004:15004"
    command: >
      redis-server --port 5004
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5004
                   --cluster-announce-bus-port 15004
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5004" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis5-data:/data
    networks:
      - app-global-network


  redis6:
    image: redis:7.2-alpine
    container_name: redis6
    ports:
      - "5005:5005"
      - "15005:15005"
    command: >
      redis-server --port 5005
                   --cluster-enabled yes
                   --cluster-config-file nodes.conf
                   --appendonly yes
                   --cluster-node-timeout 5000
                   --cluster-announce-port 5005
                   --cluster-announce-bus-port 15005
    healthcheck:
          test: ["CMD", "redis-cli", "-p" , "5005" , "ping"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 10s
    volumes:
      - redis6-data:/data
    networks:
      - app-global-network


volumes:
  redis1-data:
  redis2-data:
  redis3-data:
  redis4-data:
  redis5-data:
  redis6-data:

networks:
    app-global-network:
       external:true