version: "3.8"

services:
   nginx:
      image: ngnix:latest
      container_name: ngnix
      ports:
        - "80:80"
      healthcheck:
        test: ["CMD", "curl" , "-f" , "http://localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 10s
      volumes:
        -  ./nginx.conf:/etc/nginx/nginx.conf
      networks:
        - app-global-network
      
networks:
  app-global-network:
    external:true 
